<?php

namespace Database\Seeders;

use App\Models\Rate;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class RateImportFromSheet1 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $path = database_path('location.sql');
        // Load the SQL file content
        $sql = File::get($path);
        DB::unprepared($sql);
        $this->command->info('SQL file imported successfully!');
       $rates = [
            [


                'name' => 'Kuala Lumpur International Airport to Kuala Lumpur International Hotel',
                'package' =>'Economy',
                'from_location_id' => 1,
                'to_location_id' => 2,
                'rate' => '130.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,
                //              'user_id' => auth()->id(),

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Kuala Lumpur International Hotel',
                'package' =>'Standard',
                'from_location_id' => 1,
                'to_location_id' => 2,
                'rate' => '170.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Kuala Lumpur International Hotel',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 2,
                'rate' => '210.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Kuala Lumpur International Hotel',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 2,
                'rate' => '250.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Kuala Lumpur International Hotel',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 2,
                'rate' => '290.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Subang Jaya',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 3,
                'rate' => '130.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,
                //              'user_id' => auth()->id(),

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Subang Jaya',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 3,
                'rate' => '170.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Subang Jaya',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 3,
                'rate' => '210.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Subang Jaya',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 3,
                'rate' => '250.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Subang Jaya',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 3,
                'rate' => '290.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Sunway Lagoon',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 4,
                'rate' => '130.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,
                //              'user_id' => auth()->id(),

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Sunway Lagoon',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 4,
                'rate' => '170.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Sunway Lagoon',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 4,
                'rate' => '210.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Sunway Lagoon',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 4,
                'rate' => '250.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Sunway Lagoon',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 4,
                'rate' => '290.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Genting Malaysia Berhad',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 5,
                'rate' => '280.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Genting Malaysia Berhad',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 5,
                'rate' => '300.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Genting Malaysia Berhad',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 5,
                'rate' => '340.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Genting Malaysia Berhad',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 5,
                'rate' => '410.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Genting Malaysia Berhad',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 5,
                'rate' => '550.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Bukit Tinggi',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 6,
                'rate' => '305.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Bukit Tinggi',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 6,
                'rate' => '340.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Bukit Tinggi',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 6,
                'rate' => '380.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Bukit Tinggi',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 6,
                'rate' => '410.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Bukit Tinggi',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 6,
                'rate' => '520.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Golden Palm Tree Sea Villas & Spa',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 7,
                'rate' => '175.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Golden Palm Tree Sea Villas & Spa',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 7,
                'rate' => '210.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Golden Palm Tree Sea Villas & Spa',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 7,
                'rate' => '240.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Golden Palm Tree Sea Villas & Spa',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 7,
                'rate' => '250.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Golden Palm Tree Sea Villas & Spa',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 7,
                'rate' => '460.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Cameron Highlands',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 8,
                'rate' => '720.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Cameron Highlands',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 8,
                'rate' => '770.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Cameron Highlands',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 8,
                'rate' => '810.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Cameron Highlands',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 8,
                'rate' => '870.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Cameron Highlands',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 8,
                'rate' => '1200.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Port Dickson',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 9,
                'rate' => '305.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Port Dickson',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 9,
                'rate' => '340.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Port Dickson',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 9,
                'rate' => '410.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Port Dickson',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 9,
                'rate' => '470.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Port Dickson',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 9,
                'rate' => '590.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to A Famosa',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 10,
                'rate' => '430.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to A Famosa',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 10,
                'rate' => '440.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to A Famosa',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 10,
                'rate' => '455.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to A Famosa',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 10,
                'rate' => '520.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to A Famosa',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 10,
                'rate' => '980.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Malacca',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 11,
                'rate' => '430.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Malacca',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 11,
                'rate' => '470.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Malacca',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 11,
                'rate' => '500.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Malacca',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 11,
                'rate' => '560.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Malacca',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 11,
                'rate' => '980.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Johor Bahru',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 12,
                'rate' => '820.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Johor Bahru',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 12,
                'rate' => '870.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Johor Bahru',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 12,
                'rate' => '940.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Johor Bahru',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 12,
                'rate' => '1000.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Johor Bahru',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 12,
                'rate' => '1240.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Singapore',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 13,
                'rate' => '1105.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Singapore',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 13,
                'rate' => '1180.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Singapore',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 13,
                'rate' => '1255.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Singapore',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 13,
                'rate' => '1255.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Singapore',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 13,
                'rate' => '1255.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Ipoh',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 14,
                'rate' => '695.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Ipoh',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 14,
                'rate' => '710.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Ipoh',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 14,
                'rate' => '740.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Ipoh',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 14,
                'rate' => '810.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Ipoh',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 14,
                'rate' => '1040.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Penang',
                'package' => 'Economy',
                'from_location_id' => 1,
                'to_location_id' => 15,
                'rate' => '825.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 3,
                'vehicle_luggage_capacity' => 3,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Penang',
                'package' => 'Standard',
                'from_location_id' => 1,
                'to_location_id' => 15,
                'rate' => '940.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Penang',
                'package' => 'VAN(12 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 15,
                'rate' => '1000.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 8,
                'vehicle_luggage_capacity' => 9,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Penang',
                'package' => 'VAN(14 SEATER)',
                'from_location_id' => 1,
                'to_location_id' => 15,
                'rate' => '1070.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 12,
                'vehicle_luggage_capacity' => 13,

            ],
            [
                'name' => 'Kuala Lumpur International Airport to Penang',
                'package' => 'LUXURY CAR',
                'from_location_id' => 1,
                'to_location_id' => 15,
                'rate' => '1170.00',
                'currency' => 'MYR',
                'effective_date' => Carbon::now('Asia/Kuala_Lumpur')->format('Y-m-d'),
                'expiry_date' => Carbon::now('Asia/Kuala_Lumpur')->addYears(5)->format('Y-m-d'),
                'vehicle_seating_capacity' => 4,
                'vehicle_luggage_capacity' => 5,

            ],
        ];
        foreach ($rates as $rate) {
            Rate::create($rate);
        }
    }
}
